language: rust
compiler: clang

env:
  global: RUSTFLAGS="-D warnings" RUST_LOG=info

rust: stable

matrix:
  include:
    # Linux 64bit
    - os: linux

    # macOS 64bit
    - env: MACOSX_DEPLOYMENT_TARGET=10.9
      os: osx
      osx_image: xcode9

    # iPhoneOS 64bit
    - env: TARGET=aarch64-apple-ios
      os: osx
      osx_image: xcode9

    # Windows 64bit
    - os: windows

branches:
  only:
    - staging
    - trying
    - master

before_install:
  - if [[ $TRAVIS_OS_NAME == "windows" ]]; then choco install make; choco install ninja; fi
  - rustup self update
  - if [[ ! -z "$TARGET" ]]; then rustup target add $TARGET; fi

script:
  - make
