[package]
name = "rendy-memory"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]

[dependencies]
failure = "0.1"
veclist = "0.1"
ash = { path = "../../ash/ash" }
serde = { version = "1.0", optional = true, features = ["derive"] }
smallvec = "0.6"
hibitset = "0.5"
relevant = "0.2"
derivative = "1.0"

[dev-dependencies]
rand = "0.5"
