[package]
name = "rendy-command"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]

[dependencies]
gfx-hal = { git = "https://github.com/gfx-rs/gfx" }
derivative = "1.0"
failure = "0.1"
relevant = "0.2"
smallvec = "0.6"
rendy-resource = { path = "../resource" }
