[package]
name = "rendy-render"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]

[dependencies]
bitflags = "*"
failure = "*"
relevant = "*"
rendy-memory = { path = "../memory" }
rendy-resource = { path = "../resource" }
gfx-hal = { git = "https://github.com/gfx-rs/gfx.git", optional = true }
ash = { version = "*", optional = true }
share = "*"
