[package]
name = "rendy-command"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]

[dependencies]
ash = { git = "https://github.com/MatusT/ash.git", branch = "generator" }
failure = "0.1"
relevant = "0.2"
smallvec = "0.6"
