[package]
name = "rendy-factory"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]

[dependencies]
ash = { path = "../../ash/ash" }
derivative = "1.0"
failure = "0.1"
log = "0.4"
relevant = "0.2"
serde = { version = "1.0", optional = true, features = ["derive"] }
smallvec = "0.6"
winit = "0.17"

rendy-memory = { path = "../memory" }
rendy-resource = { path = "../resource" }
rendy-command = { path = "../command" }
rendy-wsi = { path = "../wsi" }

[target.'cfg(target_os = "macos")'.dependencies]
objc = "0.2"
cocoa = "0.18"

[dev-dependencies]
env_logger = "0.5"

