[package]
name = "rendy"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]

[dependencies]
ash = { git = "https://github.com/MatusT/ash.git", branch = "generator" }
derivative = "1.0"
failure = "0.1"
log = "0.4"
relevant = "0.2"
serde = { version = "1.0", optional = true, features = ["derive"] }
smallvec = "0.6"
winit = "0.17"

rendy-memory = { path = "../memory" }
rendy-resource = { path = "../resource" }
rendy-command = { path = "../command" }

[dev-dependencies]
env_logger = "0.5"
