[package]
name = "rendy-frame"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]

[dependencies]
gfx-hal = { git = "https://github.com/gfx-rs/gfx" }
failure = "0.1"
relevant = "0.2"
smallvec = "0.6"
rendy-command = { path = "../command" }
