[package]
name = "rendy-resource"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]

[dependencies]
bitflags = "*"
crossbeam-channel = "*"
rendy-memory = { path = "../memory" }
relevant = "*"
