[package]
name = "rendy-resource"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]

[dependencies]
bitflags = "*"
crossbeam-channel = "*"
rendy-memory = { path = "../memory" }
relevant = "*"
failure = "*"
gfx-hal = { git = "https://github.com/gfx-rs/gfx.git", optional = true }
ash = { version = "*", optional = true }

[features]
hal = ["gfx-hal", "rendy-memory/hal"]
vulkan = ["ash", "rendy-memory/vulkan"]
