[package]
name = "rendy-resource"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]

[dependencies]
crossbeam-channel = "*"
gfx-hal = { git = "https://github.com/gfx-rs/gfx.git", optional = true }
rendy-memory = { path = "../memory" }
relevant = "*"