[package]
name = "rendy-resource"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]

[dependencies]
ash = { path = "../../ash/ash" }
crossbeam-channel = "0.2"
relevant = "0.2"
rendy-memory = { path = "../memory" }
