[package]
name = "rendy-shader-proc"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]

[lib]
proc-macro = true

[dependencies]
ash = { path = "../../../ash/ash" }
shaderc = "0.3"
syn = "0.15"
quote = "0.6"
