[package]
name = "rendy-memory"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]

[dependencies]
bitflags = "*"
failure = "*"
veclist = "*"
gfx-hal = { path = "../gfx/hal", optional = true }
