[package]
name = "rendy-chain"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]

[dependencies]
ash = { git = "https://github.com/MatusT/ash.git", branch = "generator" }
fnv = "1.0"
