[package]
name = "rendy-chain"
version = "0.1.0"
authors = ["omni-viral <scareaangel@gmail.com>"]
edition = "2018"

[dependencies]
gfx-hal = { git = "https://github.com/gfx-rs/gfx" }
fnv = "1.0"
log = "0.4"
